# Generated by Django 5.2.17 on 2026-09-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0002_customer_booking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="place",
        ),
    ]
